language: java
install: true
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew build --scan -s
  - ./gradlew installDist
  - ./build-examples.sh


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/